### ISSUE TITLE
CONVERT fails on a valid JavaCC Grammar

### ISSUE THREAD

**Issue by manticore-projects** [GuntherRademacher/rr#20]
Greetings Gunther.

A certain valid JavaCC Grammar is failing with multiple constructs.
(Although the Grammar is building fine with JavaCC).

Since `Convert` is not public, I can only escalate this to you.
Thank you in advance for looking into it.
Cheers!

[parser_tmp.jjt.zip](https://github.com/GuntherRademacher/rr/files/10303557/parser_tmp.jjt.zip)

**Comment by GuntherRademacher** [comment]
This is JJTree grammar. [Convert](https://bottlecaps.de/convert) does not support it directly. What you can do is run it through JJTree, yielding a .jj file, which is then understood by Convert.
