### ISSUE TITLE
XML Parsing Error on Published Page

### ISSUE THREAD

**Issue by sebfisch** [GuntherRademacher/rr#26]
https://bottlecaps.de/rr/ui presents an XML parsing error instead of the actual page.

Firefox Screenshot:
![Screenshot 2023-10-11 111752](https://github.com/GuntherRademacher/rr/assets/38267/46c7ea96-f399-448c-a61b-8818e36ff2d6)

**Comment by mingodad** [comment]
Probably you'll need to add the input that created the error !

**Comment by GuntherRademacher** [comment]
That unclosed link element causing the XML parsing failure, `<link rel="stylesheet"...`, does not originate from [https://bottlecaps.de/rr/ui](https://bottlecaps.de/rr/ui). It must have been inserted on the client side, presumably by some browser plugin, or possibly even by malware. Also it refers to some service running on port 51991 on your local machine. You might want to check what that is, and who is doing this.
