### ISSUE TITLE
bottelcaps URLs broken

### ISSUE THREAD

**Issue by mrwatson-de** [GuntherRademacher/rr#28]
Hi Gunther,

I noticed that the URLs to www.bottlecaps.de (in the README file) are all broken.

I hope you are well.

Regards

MrWatson

**Comment by GuntherRademacher** [comment]
The URLs are fine, and the server is up and running, but it has gone IPv6-only. You are possibly trying to reach it from a point where you have an IPv4-only connection. One way to check is [https://test-ipv6.com/](https://test-ipv6.com/).

Sorry about that. But it is a private server without dedicated funding, and the switch to IPv6 is a consequence of changing my Internet connection to Deutsche Glasfaser.

**Comment by mrwatson-de** [comment]
Hi,


> On 8. Jan 2024, at 14:23, Gunther Rademacher ***@***.***> wrote:
> 
> 
> The URLs are fine, and the server is up and running, but it has gone IPv6-only. You are possibly trying to reach it from a point where you have an IPv4-only connection. One way to check is https://test-ipv6.com/.
> 
Thanks for the tip - and indeed you seem to be right! Good to know!

￼

> Sorry about that. But it is a private server without dedicated funding, and the switch to IPv6 is a consequence of changing my Internet connection to Deutsche Glasfaser.
> 
No worries, I'll see if I can get myself IP6-ready. Congratulations! You're the first IPv6 only website I've seen…we're moving slowly but surely into the future!

I'll try my mobile ;-)

Regards

***@***.***

**Comment by asmaloney** [comment]
Just ran into this too - it's kind of buried in the "closed issues". Would this be worth adding to the readme? Or can you pin a closed issue?

(I too will have to wrestle with my ISP to get it sorted out. I guess 25+ years should be enough time to get ready for it 😆 )

Thanks!
