### ISSUE TITLE
Your website (www.bottlecaps.de) seems to be down for users who don't have IPv6 - any plans to fix that?

### ISSUE THREAD

**Issue by vsajip** [GuntherRademacher/rr#31]
Thanks very much for this software, it's really useful and looks very nice, too! I've noticed over the past week that I can't access `www.bottlecaps.de` any more from my home network (which is running IPv4 only - no IPv6 support). I've confirmed that DNS appears to only return an IPv6 address:
```console
$ nslookup www.bottlecaps.de
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
www.bottlecaps.de	canonical name = bottlecaps.dynv6.net.
Name:	bottlecaps.dynv6.net
Address: 2a00:6020:5044:f400:92b1:1cff:fe97:fdae
```
Do you have any plans to reinstate IPv4 support?

**Comment by alerque** [comment]
Duplicate of #28 (which should probably be pinned even though it is closed).

**Comment by vsajip** [comment]
I'm willing to try hosting this on a server I have available, since I don't have IPv6 available through my ISP :cry:  @GuntherRademacher, would this be acceptable to you? It would probably be on a domain such as `rr.red-dove.com` (`red-dove.com` is a domain I own).

**Comment by vsajip** [comment]
Thanks for the tip about Tor. I know the license allows the code to be used, and I do use it locally - but clearly I'm not the only one who has no IPv6 available, and I sometimes work from different sites and might want to have access when I'm there. Just offering an alternative - and since Gunther's name is on the web interface, I thought I would ask him as a courtesy. I was thinking of making minor changes to a version I host to mention that the site isn't the official one, why it exists, etc.

**Comment by Monotoba** [comment]
I've used this tool for years and it is my go-to tool for visualizing grammars for DSLs I code. For years it has been one of the very first bookmarks on any machine I own. I was very surprised when I found that after several years of using this wonderful tool, I could no-longer access it. When did this change? And is it only those with ipv4 that have issues? Ive got a server in a data center but I run an apache lamp stack and no tomcat. Perhaps I should look into setting up something that can run this. Anyone know if apache supporting php and python can also support tomcat and how to set it up?

**Comment by vsajip** [comment]
You don't need Tomcat; I just run `java -jar rr.war -gui -port:NNNN` using a process control system such as Supervisor (to control restarts etc.) and proxy to that port from nginx. I expect you can do the same with Apache.

**Comment by GuntherRademacher** [comment]
> Do you have any plans to reinstate IPv4 support?

Sorry, but no.

**Comment by GuntherRademacher** [comment]
> @GuntherRademacher, would this be acceptable to you? It would probably be on a domain such as `rr.red-dove.com` (`red-dove.com` is a domain I own).

Fine by me.

**Comment by GuntherRademacher** [comment]
> Perhaps I should look into setting up something that can run this.

To run it standalone from a command line, you need nothing but a JRE (at least Java 11) and [rr.war](https://github.com/GuntherRademacher/rr/releases/download/v2.1/rr-2.1-java11.zip). I usually do this with this command:

```bash
java -jar rr.war -gui -port:8001
```

and then access http://localhost:8001 from the browser.

**Comment by GuntherRademacher** [comment]
> I just run `java -jar rr.war -gui -port:NNNN` using a process control system such as Supervisor (to control restarts etc.) and proxy to that port from nginx.

Note that this uses the JRE's internal HTTP server. I am unsure about the multi-user behavior of this approach, so you might want to run some tests. Otherwise I'd rather use a real servlet container.

**Comment by Monotoba** [comment]
Thanks for the info. I apache has a powerful forward/reverse proxy system
so I can make that work!

**Comment by vsajip** [comment]
I have made it available on https://rr.red-dove.com/ - thank you Gunther! I'm assuming for now that the JRE internal HTTP server should be fine, but we'll see.

**Comment by GuntherRademacher** [comment]
> I have made it available on https://rr.red-dove.com/

Thanks a lot. I have added a link to [README.md](https://github.com/GuntherRademacher/rr/blob/master/README.md#links).

**Comment by GuntherRademacher** [comment]
@vsajip Just a quick update to let you know that my server is now back in IPv4 space. Thank you for your help while it was IPv6-only! You can stop running RR on your server now if you'd like, but feel free to continue if it works for you - entirely up to you.

**Comment by mingodad** [comment]
Nice to know !
All the links I've done in the past come alive again !
Also I've noticed that you also released the `REX` parser generator. That's nice thank you !
