### ISSUE TITLE
Direct recursion elimination produces duplicate path

### ISSUE THREAD

**Issue by PhilippSalvisberg** [GuntherRademacher/rr#43]
Thanks for this excellent tool. I use it to visualize a SQL grammar. Here's a small excerpt of the grammar to reproduce the problem:

```
dataType ::=
      oracleBuiltInDatatype
    | ansiSupportedDatatype
    | postgresqlDatatype
    | userDefinedType
    | dataType (LSQB RSQB)+

LSQB ::=  '['
RSQB ::=  ']'
```

I use the following settings with the current version (8773d49e0d0dff4767ac094bfeb28c56d4a35e25) of the master branch.

![image](https://github.com/GuntherRademacher/rr/assets/3883171/01f509dd-1998-4306-99c9-d6956d8e1b68)

The result looks like this:

![image](https://github.com/GuntherRademacher/rr/assets/3883171/aa5059eb-079b-4698-8c4d-c8549fd4fc94)

I highlighted the duplicate path. 

The result looks good when I disable the "Direct recursion elimination" option. Like this:

![image](https://github.com/GuntherRademacher/rr/assets/3883171/3e2eac92-528b-418f-b825-2a51581f2212)

Disabling the option as a workaround is good enough for me.

**Comment by mingodad** [comment]
It seems that you do not need the `+` in `| dataType (LSQB RSQB)+`.

**Comment by PhilippSalvisberg** [comment]
> The `+` is not required the left recursive rule `| dataType LSQB RSQB` already mean a `dataType` followd by one or more `LSQB RSQB`.

Oh you are correct @mingodad. I haven't seen that.

**Comment by PhilippSalvisberg** [comment]
Based on the comment of @mingodad I think the visualization is correct. Enabling "Direct recursion elimination" just showed a flaw in the grammar.

I'm closing this issue. Thanks @mingodad.
