### ISSUE TITLE
Repetition with braces?

### ISSUE THREAD

**Issue by Blady-Com** [GuntherRademacher/rr#53]
I have the following grammar snippet: 
```
declarative_part ::= declarative_item {declarative_item}
  declarative_item ::= basic_declarative_item | body
  basic_declarative_item ::= basic_declaration | aspect_clause
  basic_declaration ::=
             null_declaration
           | type_declaration
           | subtype_declaration
           | object_declaration
           | named_value_declaration
           | subprogram_declaration
           | statement_procedure_declaration
           | expression_function_declaration
           | module_declaration
           | renaming_declaration
           | exception_declaration
           | macro_declaration
           | macro_expansion
```
I got the error:
```
error: lexical analysis failed
while expecting [Whitespace, NCName, Context, StringLiteral, CharCode, '/*ws:explicit*/', '/*ws:definition*/', DocComment, EOF, EquivalenceLookAhead, '$', '&', '(', ')', '*', '+', '-', '.', '/', '::=', '<<', '<?', '<?ENCORE?>', '<?TOKENS?>', '>>', '?', '[', '[^', '\\', '|']
at line 1, column 40:
```
The following is ok:
` declarative_part ::= declarative_item declarative_item*`
Nevertheless, aren't braces a regular EBNF repetition pattern?
How to get braces support with RR?

**Comment by mingodad** [comment]
The grammar used by `rr` is here https://github.com/GuntherRademacher/rr/blob/master/src/main/java/de/bottlecaps/railroad/core/Parser.ebnf and the only repetiton operators are here :
https://github.com/GuntherRademacher/rr/blob/9795781d075d89c8596ed7609ba9614938f081c6/src/main/java/de/bottlecaps/railroad/core/Parser.ebnf#L25

**Comment by mingodad** [comment]
Now that I posted and looking at it shouldn't the repetition operators be optional instead of zero or more ?
```
Item                  ::= Primary ( '?' | '*' | '+' )?
```

**Comment by GuntherRademacher** [comment]
> How to get braces support with RR?

As pointed out by @mingodad, you are using a different syntax for repetitions than is supported by RR.

However, your grammar is understood by the `instaparse-to-w3c` converter in [ebnf-convert](https://www.bottlecaps.de/ebnf-convert/), so you could paste it there to convert it, and then proceed to RR by clicking `View Diagram`. Alternatively, run either on command line.

**Comment by GuntherRademacher** [comment]
> Now that I posted and looking at it shouldn't the repetition operators be optional instead of zero or more ?
> 
> ```
> Item                  ::= Primary ( '?' | '*' | '+' )?
> ```

No, because RR  treats sequences of occurrence indicators like if they were applied to a parenthesized operand, i.e. `A+?` is treated like `((A)+)?` and eventually transformed to `A*`. Making them optional would turn the unparenthesized version invalid.

**Comment by mingodad** [comment]
>Making them optional would turn the unparenthesized version invalid.

And wouldn't it make sense to do so ?

**Comment by mingodad** [comment]
Because people can expect it to mean non greed matching.

**Comment by Blady-Com** [comment]
> > How to get braces support with RR?
> 
> As pointed out by @mingodad, you are using a different syntax for repetitions than is supported by RR.
> 
> However, your grammar is understood by the `instaparse-to-w3c` converter in [ebnf-convert](https://www.bottlecaps.de/ebnf-convert/), so you could paste it there to convert it, and then proceed to RR by clicking `View Diagram`. Alternatively, run either on command line.

Thanks all for your answers.
I'll give a try.

**Comment by GuntherRademacher** [comment]
> > Making them optional would turn the unparenthesized version invalid.
> 
> And wouldn't it make sense to do so ?

@mingodad I guess you are right, I am not aware of a use case for the current behavior. So I have changed it accordingly (e3808f357da5145831fc69df2e2a3d5626fde2ae) - thank you for your hint.

Also, the upcoming [XQuery 4.0](https://qt4cg.org/specifications/xquery-40/xquery-40.html#EBNFNotation) specification is introducing new repetition operators with separators, `**` and `++`, borrowed from [Invisible XML](https://invisiblexml.org/1.0/), and I have taken a very first step to support them in RR (d099960ebe906e0077fe22e9696a1d2b59275787).
