### ISSUE TITLE
Can't have close square brackets escaped inside ranges

### ISSUE THREAD

**Issue by mingodad** [GuntherRademacher/rr#6]
Testing a bash grammar I found that `rr` doesn't accept close square bracket escaped inside ranges (open square brackets it's OK):
```
nonsquarebra ::=  [^\[\]]
```
Output:
```
lexical analysis failed
while expecting [Whitespace, NCName, StringLiteral, CharCode, '/*ws:explicit*/', '/*ws:definition*/', DocComment, EOF, EquivalenceLookAhead, '$', '&', '(', ')', '*', '+', '-', '.', '/', '<?', '<?ENCORE?>', '<?TOKENS?>', '?', '[', '[^', '|']
at line 1, column 25:
...]...
```

**Comment by myCrack** [comment]
> `nonsquarebra ::=  [^\[\]]`

You can rewrite it like this:
```ebnf
nonsquarebra ::= [^#x005B#x005D]`
````

**Comment by mingodad** [comment]
Thank you for reply !
Would be nice if `rr` had an option to relax/accept common escaped sequences `\t\r\n\s\S\w\W...` or even regular expressions like `/.../`.

**Comment by myCrack** [comment]
> Would be nice if `rr` had an option to relax/accept common escaped sequences `\t\r\n\s\S\w\W...` or even regular expressions like `/.../`.

RR use ebnf defined by w3c, so i think it is a bad idea.

**Comment by mingodad** [comment]
That's why I said "Would be nice if rr had an option to **relax/accept** common escaped sequences" meaning the user would need to check this in the **Options** tab.

**Comment by mingodad** [comment]
Also I did converted (naively) several grammars from **tree-sitter** to the **EBNF** supported by this project here https://github.com/mingodad/plgh, would be nice to have a link to then in https://www.bottlecaps.de/rr/ui

**Comment by GuntherRademacher** [comment]
There are no plans to extend the grammar syntax. Please use the notation as already pointed out by @myCrack above.
