### ISSUE TITLE
Do not generate duplicated svg styles

### ISSUE THREAD

**Issue by mingodad** [GuntherRademacher/rr#9]
It seems that is possible to not emit the same style in each `svg` and still been able to view it correctly, saving around 1/4 of the actual xhtml.
```
---------- src/main/resources/de/bottlecaps/railroad/xq/ast-to-svg.xq ----------
@@ -1053,7 +1054,6 @@ declare function s:convert-to-svg($p as element(g:production), $page-width as xs
     <svg xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          width="{$width + 1}" height="{$height + 1}">
-      <defs>{s:style($color, $spread)}</defs>
       {
         s:translate(1 - xs:integer($dimensions/@x1), 1 - xs:integer($dimensions/@y1), $rendered)
       }
```

**Comment by manticore-projects** [comment]
Greetings. I have tried that and it does not work.
I have not been able to see the Diagrams in FireFox after removing the styles. Replacing with a reference to a CSS file seems to be the better option.

**Comment by GuntherRademacher** [comment]
Yes, that works. But it is not quite sufficient. The conversion to HTML+PNG and MD (not advertised) relies on the fact that the XHTML brings self-contained SVGs. So that has to be adapted as well.

**Comment by GuntherRademacher** [comment]
Now fixed in [v1.65](https://github.com/GuntherRademacher/rr/releases/tag/v1.65).

**Comment by mingodad** [comment]
Thank you !
There any news in opensourcing of [convert](https://www.bottlecaps.de/convert/) and https://www.bottlecaps.de/rex/ ?

**Comment by GuntherRademacher** [comment]
> There are any news in opensourcing of [convert](https://www.bottlecaps.de/convert/) and https://www.bottlecaps.de/rex/ ?

Not my main focus at the moment. To come one day

**Comment by mingodad** [comment]
Again thank you !
